projeto1/projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

projeto1/recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name='home'),
    path('recipes/<uuid:id>/', views.recipe, name='recipe')
]

projeto1/recipes/models.py
from django.db import models

# Create your models here.

projeto1/recipes/views.py
from django.shortcuts import render
from .utils.recipes.factory import make_recipe

def home(request):
    return render(request, 'recipes/pages/home.html', context={
        'name': 'Heitor Claudino',
        'recipes': [make_recipe() for _ in range(10)]
    })

def recipe(request, id):
    return render(request, 'recipes/pages/recipe-view.html', context={
        'name': 'Heitor Claudino',
        'recipe': make_recipe(),
        'is_detail_page': True
    })

projeto1/recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home |{% endblock title %}

{% block content %}
    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% include 'recipes/partials/recipe.html' %}
        {% endfor %}
    </div>
{% endblock content %}

projeto1/recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}

{% block title %}Minha Receita |{% endblock title %}

{% block content %}
    <div class="main-content main-content-detail container">
        {% include 'recipes/partials/recipe.html' %}
    </div>
{% endblock content %}

projeto1/recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
        <a href="https://www.otaviomiranda.com.br/" target="_blank" rel="noreferrer noopener">By {{ name }}</a>
    </div>
    <div class="powered">
        <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
</footer>

projeto1/recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/brands.min.css"
      integrity="sha512-58P9Hy7II0YeXLv+iFiLCv1rtLW47xmiRpC1oFafeKNShp8V5bKV/ciVtYqbk2YfxXQMt58DjNfkXFOn62xE+g=="
      crossorigin="anonymous" referrerpolicy="no-referrer"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/fontawesome.min.css"
      integrity="sha512-v8QQ0YQ3H4K6Ic3PJkym91KoeNT5S3PnDKvqnwqFD1oiqIl653crGZplPdU5KKtHjO0QKcQ2aUlQZYjHczkmGw=="
      crossorigin="anonymous" referrerpolicy="no-referrer"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/solid.min.css"
      integrity="sha512-DzC7h7+bDlpXPDQsX/0fShhf1dLxXlHuhPBkBo/5wJWRoTU6YL7moeiNoej6q3wh5ti78C57Tu1JwTNlcgHSjg=="
      crossorigin="anonymous" referrerpolicy="no-referrer"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'global/css/global-styles.css' %}">

projeto1/recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'recipes:home' %}">
                <i class="fa-solid fa-utensils main-logo-icon"></i>
                <span class="main-logo-text">RECIPES</span>
            </a>
        </h1>
    </div>
</header>

projeto1/recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{% url 'recipes:recipe' recipe.id %}">
            <img src="{{ recipe.cover.url }}" alt="Temporário">
        </a>
    </div>
    <div class="recipe-title-container">
        <a href="{% url 'recipes:recipe' recipe.id %}">
            <h2 class="recipe-title">{{ recipe.title }}</h2>
        </a>
    </div>
    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {{ recipe.author.first_name }} {{ recipe.author.last_name }}
        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y" }} às {{ recipe.created_at|date:"H:i" }}
        </span>
        <span class="recipe-author-item">
            <a href="/recipes/category/cafe-da-manha/">
                <i class="fas fa-layer-group"></i>
                <span>{{ recipe.category.name }}</span>
            </a>
        </span>
    </div>
    <div class="recipe-content">
        <p>
            {{ recipe.description }}
        </p>
    </div>
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>

    {% if is_detail_page is True %}
    <div class="preparation-steps">
        {{ recipe.preparation_steps|linebreaksbr }}
    </div>
    {% endif %}

    {% if is_detail_page is not True %}
    <footer class="recipe-footer">
        <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
            <i class="fas fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
    {% endif %}
</div>

projeto1/recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search" autocomplete="off">
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>

projeto1/recipes/templates/recipes/patials/head.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/brands.min.css"
          integrity="sha512-58P9Hy7II0YeXLv+iFiLCv1rtLW47xmiRpC1oFafeKNShp8V5bKV/ciVtYqbk2YfxXQMt58DjNfkXFOn62xE+g=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/fontawesome.min.css"
          integrity="sha512-v8QQ0YQ3H4K6Ic3PJkym91KoeNT5S3PnDKvqnwqFD1oiqIl653crGZplPdU5KKtHjO0QKcQ2aUlQZYjHczkmGw=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/solid.min.css"
          integrity="sha512-DzC7h7+bDlpXPDQsX/0fShhf1dLxXlHuhPBkBo/5wJWRoTU6YL7moeiNoej6q3wh5ti78C57Tu1JwTNlcgHSjg=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
    <title>Home - Recipes</title>

    <style>
        * {
            padding: 0px;
            margin: 0px;
            box-sizing: border-box;
        }

        :root {
            --color-primary: #269fe6;
            --color-primary-hover: #2086c2;
            --color-primary-dark: #13141f;
            --color-primary-dark-hover: #212336;
            --color-primary-light: #d4ecfa;
            --color-primary-light-hover: #bdd8e7;
            --color-white: #fff;
            --color-black: #000;
            --color-dark-text: #444;
            --color-info-light: #cce5ff;
            --color-debug-light: #cce5ff;
            --color-success-light: #d4edda;
            --color-alert-light: #fff3cd;
            --color-warning-light: #fff3cd;
            --color-error-light: #f8d7da;
            --color-info-dark: #4d86c4;
            --color-debug-dark: #4d86c4;
            --color-success-dark: #4a9c5d;
            --color-alert-dark: #927f40;
            --color-warning-dark: #927f40;
            --color-error-dark: #da525d;
            --color-gray-0: #f9f9f9;
            --color-gray-1: #e0e0e0;
            --color-gray-2: #c7c7c7;
            --color-gray-3: #aeaeae;
            --color-gray-4: #959595;
            --color-gray-5: #7d7d7d;
            --color-gray-6: #646464;
            --color-gray-7: #4b4b4b;
            --color-gray-8: #323232;
            --color-gray-9: #191919;
            --font-primary: sans-serif;
            --font-headings: 'Roboto Slab', serif;
            --spacing-gutter-medium: 3rem;
            --spacing-gutter-large: 4rem;
        }

        html {
            font-size: 62.5%;
        }

        body {
            font-size: 1.6rem; /* 1.6rem = 16px */
            font-family: var(--font-primary);
            background-color: var(--color-gray-1);
        }

        h1, h2, h3, h4, h5, h6 {
            font-family: var(--font-headings);
        }

        .container {
            max-width: 144rem;
            margin: 0 auto;
            padding: var(--spacing-gutter-medium);
        }

        .main-header-container {
            background-color: var(--color-primary-dark);
        }

        .main-logo {
            color: var(--color-white);
            font-size: 4rem;
            text-decoration: none;
            display: flex;
            flex-flow: row nowrap;
            align-items: center;
            width: fit-content;
            margin: 0 auto;
        }

        .main-logo-icon {
            margin-right: 2rem;
        }

        .search-form {
            border: .2rem solid var(--color-primary-dark);
            max-width: 64rem;
            margin: 0 auto;
            border-radius: .4rem;
            position: relative;
            transition: all 300ms ease-in-out;
        }

        .search-input,
        .search-button {
            border: none;
            background: none;
            outline: none;
            padding: 1rem;
            transition: all 300ms ease-in-out;
        }

        .search-input {
            width: 100%;
            padding-right: 3rem;
        }

        .search-button {
            position: absolute;
            top: 0;
            right: 0;
        }

        .search-button:focus {
            outline: 1px solid var(--color-primary);
            background: rgba(0, 0, 0, .05)
        }

        .search-form:focus-within {
            border-color: var(--color-primary);
            background: var(--color-white);
        }

        .search-form:focus-within .search-button {
            color: var(--color-primary);
        }
    </style>
</head>